networks:
  app-network:
    driver: bridge

services:
  client:
    container_name: frontend
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=my_password_is_very_puriramchick
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx
    networks:
      - app-network