name: Start XUnit Tests

on:
    push:
        branches: [main, dev]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest

        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
    
          - name: Set up .NET
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '8.x'

          - name: Restore dependencies
            run: dotnet restore ./RussianRouletteBut.sln
            
          - name: Build the solution
            run: dotnet build ./RussianRouletteBut.sln --configuration Release --no-restore
             
          - name: Run unit tests with report
            run: dotnet test ./XUnitTestProject/XUnitTestProject.csproj --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"
            
          - name: Upload test results
            uses: actions/upload-artifact@v4
            with:
              name: test-results
              path: XUnitTestProject/TestResults/test-results.trx
